/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start: () => void;
export const __wbg_peernode_free: (a: number, b: number) => void;
export const peernode_spawn: (a: number, b: number, c: number, d: number) => any;
export const peernode_events: (a: number) => any;
export const peernode_node_id: (a: number) => [number, number];
export const peernode_secret_key: (a: number) => [number, number];
export const peernode_connect: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const peernode_get_pending_requests: (a: number) => any;
export const peernode_approve_request: (a: number, b: number, c: number) => any;
export const peernode_reject_request: (a: number, b: number, c: number, d: number, e: number) => any;
export const peernode_add_trusted_issuer: (a: number, b: number, c: number) => any;
export const peernode_remove_trusted_issuer: (a: number, b: number, c: number) => any;
export const peernode_is_trusted_issuer: (a: number, b: number, c: number) => any;
export const peernode_get_trusted_issuers: (a: number) => any;
export const peernode_get_verified_credentials: (a: number) => any;
export const peernode_get_verified_credential: (a: number, b: number, c: number) => any;
export const peernode_get_received_credentials: (a: number) => any;
export const peernode_get_received_credential: (a: number, b: number, c: number) => any;
export const generate_key: () => [number, number];
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_7: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h595f4163325b68dc: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h78016f0c535c1275: (a: number, b: number) => void;
export const closure1762_externref_shim: (a: number, b: number, c: any) => void;
export const closure3138_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5c1ccd3ccc4abe59: (a: number, b: number) => void;
export const closure1419_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7131e44d0d2d72d1: (a: number, b: number) => void;
export const closure3173_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
